x-deploy: &default-deploy
  restart_policy:
    condition: unless-stopped
    delay: 5s
    window: 120s
  update_config:
    order: start-first

services:
  firezone:
    image: firezone/firezone:0.7.36
    container_name: firezone
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "51820:51820/udp"
    networks:
      firezone-network:
        ipv4_address: 172.25.0.100
        ipv6_address: fcff:3990:3990::99
      traefik-network:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"

      # Routers
      - "traefik.http.routers.firezone.rule=Host(`${FIREZONE_SERVER_HOSTNAME}`)"
      - "traefik.http.routers.firezone.entrypoints=websecure"
      - "traefik.http.routers.firezone.tls.certresolver=le-cloudflare"
      - "traefik.http.routers.firezone.service=firezone"

      # Services
      - "traefik.http.services.firezone.loadbalancer.server.port=13000"
    volumes:
      - ./.docker/firezone/data:/var/firezone
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: [ "CMD-SHELL", "nc -z 127.0.0.1 13000 || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    deploy:
      <<: *default-deploy

  postgres:
    image: postgres:15
    container_name: firezone-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-firezone}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?err}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - firezone-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    deploy:
      <<: *default-deploy
      update_config:
        order: stop-first


volumes:
  postgres-data:


networks:
  firezone-network:
    enable_ipv6: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
        - subnet: fcff:3990:3990::/64
          gateway: fcff:3990:3990::1
  traefik-network:
    external: true
